name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl tkinterdnd2

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SetAllChartsWhiteBackground-${{ runner.os }}
        path: dist/