name: Build Cross-Platform Executables

on:
  push:
    tags: ["v*"]
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Local\pip\Cache
          venv/
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller tkinterdnd2 openpyxl python-tkdnd

    - name: Build Windows EXE
      shell: pwsh
      run: |
        $tkdnd_path = python -c "import os, tkinterdnd2; print(os.path.dirname(tkinterdnd2.__file__))"
        pyinstaller --onefile --noconsole --name ExcelChartTool `
          --hidden-import tkinterdnd2 `
          --add-data "$tkdnd_path;tkdnd" `
          src/main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-excel-tool
        path: dist\ExcelChartTool.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install GUI dependencies
      run: |
        brew install --cask xquartz
        brew install tcl-tk
        echo "TCL_LIBRARY=$(brew --prefix tcl-tk)/lib" >> $GITHUB_ENV
        echo "TK_LIBRARY=$(brew --prefix tcl-tk)/lib" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app tkinterdnd2 openpyxl

    - name: Build macOS App
      run: |
        py2applet --make-setup src/main.py
        
        TK_DND_PATH=$(python -c "import os, tkinterdnd2; print(os.path.dirname(tkinterdnd2.__file__))")
        
        perl -i -pe 'BEGIN{undef $/;} s/(APP = \[.+\])/$1\nAPP_DATA = {"resources": ["$ENV{TK_DND_PATH}"]}/g' setup.py
        
        python setup.py py2app

    - name: Create PKG
      run: |
        pkgbuild --root dist/ExcelChartTool.app \
          --identifier com.example.excelchart \
          --version $(echo ${{ github.ref_name }} | sed 's/^v//') \
          --install-location /Applications \
          dist/ExcelChartTool.pkg

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-excel-tool
        path: dist/ExcelChartTool.pkg
